version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: confession_game_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: confession_game
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - confession_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d confession_game"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: confession_game_redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - confession_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    container_name: confession_game_adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - confession_network
    depends_on:
      - postgres
    environment:
      ADMINER_DEFAULT_SERVER: postgres

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: confession_game_redis_commander
    restart: unless-stopped
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    networks:
      - confession_network
    depends_on:
      - redis

volumes:
  postgres_data:
  redis_data:

networks:
  confession_network:
    driver: bridge